'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class XAAS_MultiEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=XAAS_MultiEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tbl_LoanScheduleDetail() As DbSet(Of tbl_LoanScheduleDetail)
    Public Overridable Property Tbl_Vendors() As DbSet(Of Tbl_Vendors)
    Public Overridable Property Memcos_Reg_table() As DbSet(Of Memcos_Reg_table)
    Public Overridable Property tbl_bankgl() As DbSet(Of tbl_bankgl)
    Public Overridable Property tbl_Inventorycategory() As DbSet(Of tbl_Inventorycategory)
    Public Overridable Property tbl_InventorySupply() As DbSet(Of tbl_InventorySupply)
    Public Overridable Property tbl_InventoryVendors() As DbSet(Of tbl_InventoryVendors)

End Class
